let results=[],timer=null,started=0;const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function srcs(){const o={};all('[data-s]').forEach(x=>o[x.dataset.s]=x.checked);return o;}function status(t){$('#status').textContent=t;}
function render(target='#resultList',data=results){const l=$(target);l.innerHTML='';const filter=target==='#resultList'?$('#kindFilter').value:'';const shown=data.filter(r=>!filter||r.kind===filter);for(const r of shown){const d=document.createElement('div');d.className='result';const meta=Object.entries(r).filter(([k,v])=>!['source','title','url','kind'].includes(k)&&v!==undefined&&v!==null&&v!=='').slice(0,12).map(([k,v])=>`${k}: ${typeof v==='object'?JSON.stringify(v):v}`).join(' · ');d.innerHTML=`<span class="badge">${esc(r.source)}</span><div><div class="kind">${esc(r.kind||'Record')}</div><h3>${esc(r.title||'Untitled')}</h3><div class="meta">${esc(meta)}</div></div><button>${r.url?'Open':'Details'}</button>`;d.querySelector('button').onclick=()=>r.url&&window.api.open(r.url);l.appendChild(d);}if(target==='#resultList')$('#count').textContent=`${shown.length} / ${results.length} results`;}
function kinds(){const f=$('#kindFilter'),c=f.value,ks=[...new Set(results.map(r=>r.kind).filter(Boolean))].sort();f.innerHTML='<option value="">All result types</option>'+ks.map(k=>`<option>${esc(k)}</option>`).join('');f.value=c;}
all('#tabs button').forEach(b=>b.onclick=()=>{all('#tabs button').forEach(x=>x.classList.remove('active'));all('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#panel-${b.dataset.tab}`).classList.add('active');});
$('#getSmiles').onclick=async()=>{try{$('#query').value=await $('#ketcher').contentWindow.ketcher.getSmiles();$('#mode').value='Exact structure';}catch(e){status(e.message)}};$('#getRxn').onclick=async()=>{try{const x=await $('#ketcher').contentWindow.ketcher.getSmiles();$('#query').value=x;$('#reactionInput').value=x;$('#mode').value='Reaction';}catch(e){status(e.message)}};$('#clear').onclick=async()=>{try{await $('#ketcher').contentWindow.ketcher.setMolecule('')}catch{}};
$('#search').onclick=async()=>{const q=$('#query').value.trim();if(!q)return;$('#search').disabled=true;$('#stop').disabled=false;started=Date.now();const limit=Number($('#duration').value);timer=setInterval(()=>{const s=Math.floor((Date.now()-started)/1000);status(`Searching… ${s}s elapsed, ${Math.max(0,limit-s)}s remaining`)},1000);try{results=await window.api.search({query:q,mode:$('#mode').value,sources:srcs(),duration:limit});kinds();render();status(`Completed. ${results.length} unified records.`);}catch(e){status(e.message)}finally{clearInterval(timer);$('#search').disabled=false;$('#stop').disabled=true;}};$('#stop').onclick=async()=>{clearInterval(timer);await window.api.cancelSearch();status('Cancelled.');$('#search').disabled=false;$('#stop').disabled=true;};$('#kindFilter').onchange=()=>render();
$('#save').onclick=async()=>{let structure='';try{structure=await $('#ketcher').contentWindow.ketcher.getKet()}catch{}const p=await window.api.save({version:3,saved:new Date().toISOString(),query:$('#query').value,mode:$('#mode').value,structure,reaction:$('#reactionInput').value,results,title:$('#projectTitle').value,notes:$('#notes').value});if(p)status(`Saved: ${p}`)};$('#load').onclick=async()=>{const p=await window.api.load();if(!p)return;$('#query').value=p.query||'';$('#mode').value=p.mode||'Identifier / name';$('#reactionInput').value=p.reaction||'';$('#projectTitle').value=p.title||'';$('#notes').value=p.notes||'';results=p.results||[];kinds();render();try{if(p.structure)await $('#ketcher').contentWindow.ketcher.setMolecule(p.structure)}catch{}status('Project loaded.')};
$('#export').onclick=async()=>{const ext=(prompt('Export format: csv, json, bibtex, ris','csv')||'').toLowerCase();if(!ext)return;let content='';if(ext==='json')content=JSON.stringify(results,null,2);else if(ext==='bibtex')content=results.filter(r=>r.doi).map((r,i)=>`@article{crw${i+1},\n title={${r.title||''}},\n doi={${r.doi}},\n year={${r.year||''}}\n}`).join('\n\n');else if(ext==='ris')content=results.map(r=>`TY  - GEN\nTI  - ${r.title||''}\nDO  - ${r.doi||''}\nUR  - ${r.url||''}\nER  -`).join('\n\n');else content='Source,Kind,Title,URL,Data\n'+results.map(r=>[r.source,r.kind,r.title,r.url,JSON.stringify(r)].map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');const p=await window.api.export({name:`chemical-results.${ext}`,ext,type:ext.toUpperCase(),content});if(p)status(`Exported: ${p}`)};
all('[data-url]').forEach(b=>b.onclick=()=>window.api.open(b.dataset.url));all('[data-search-url]').forEach(b=>b.onclick=()=>{const panel=b.closest('.panel')?.id;let q=panel==='panel-safety'?$('#safetyQuery').value:panel==='panel-spectra'?$('#spectraQuery').value:$('#litQuery').value;window.api.open(b.dataset.searchUrl+encodeURIComponent(q));});
$('#analyzeReaction').onclick=async()=>{const r=await window.api.analyzeReaction($('#reactionInput').value.trim());$('#reactionReport').textContent=r.ok?JSON.stringify(r,null,2):r.error};$('#copyReactionToSearch').onclick=()=>{$('#query').value=$('#reactionInput').value;$('#mode').value='Reaction';document.querySelector('[data-tab="search"]').click();};
$('#runRetro').onclick=async()=>{try{$('#retroResults').textContent='Running…';const r=await window.api.retrosynthesis({smiles:$('#retroSmiles').value,maxDepth:Number($('#retroDepth').value),iterations:Number($('#retroIterations').value)});$('#retroResults').textContent=JSON.stringify(r,null,2);}catch(e){$('#retroResults').textContent=e.message}};
$('#litSearch').onclick=async()=>{const q=$('#litQuery').value.trim();if(!q)return;render('#litResults',await window.api.search({query:q,mode:'Literature',sources:{europepmc:true,crossref:true,pubmed:true,openalex:true}}));};$('#bioSearch').onclick=async()=>{const q=$('#bioQuery').value.trim();if(!q)return;render('#bioResults',await window.api.search({query:q,mode:'Bioactivity',sources:{chembl:true,rhea:true,uniprot:true}}));};
$('#importLocal').onclick=async()=>{const r=await window.api.importLocal();$('#localStatus').textContent=`${r.count} local records loaded.`};$('#localSearch').onclick=async()=>{const d=await window.api.searchLocal($('#localQuery').value);render('#localResults',d);$('#localStatus').textContent=`${d.length} matching local records.`};
$('#calcMass').onclick=()=>$('#calcResult').textContent=`Mass = ${(Number($('#mw').value)*Number($('#mmol').value)).toFixed(3)} mg`;$('#calcMmol').onclick=()=>$('#calcResult').textContent=`Amount = ${(Number($('#massmg').value)/Number($('#mw').value)).toFixed(4)} mmol`;$('#calcVolume').onclick=()=>$('#calcResult').textContent=`Volume = ${(Number($('#mmol').value)/Number($('#conc').value)).toFixed(4)} mL`;$('#calcYield').onclick=()=>$('#calcResult').textContent=`Isolated mass = ${(Number($('#mw').value)*Number($('#mmol').value)*Number($('#yield').value)/100).toFixed(3)} mg`;
$('#saveNotebook').onclick=async()=>{const md=`# ${$('#projectTitle').value||'Chemical Research Project'}\n\nGenerated: ${new Date().toISOString()}\n\n## Query\n${$('#query').value}\n\n## Notes\n${$('#notes').value}\n\n## Selected results\n${results.slice(0,100).map(r=>`- **${r.title}** — ${r.source}${r.url?` — ${r.url}`:''}`).join('\n')}`;await window.api.saveNotebook(md)};
async function loadSettings(){const s=await window.api.loadSettings();for(const id of ['casClient','elsevierKey','epoKey','proxyUrl','retroUrl'])if(s[id]!==undefined&&$('#'+id))$('#'+id).value=s[id];}$('#saveSettings').onclick=async()=>{const s={};for(const id of ['casClient','elsevierKey','epoKey','proxyUrl','retroUrl'])s[id]=$('#'+id)?.value||'';await window.api.saveSettings(s);alert('Settings saved encrypted where supported.')};$('#testCustom').onclick=async()=>{try{const r=await window.api.runCustomConnector({url:$('#customUrl').value,query:$('#query').value,apiKey:$('#customKey').value});$('#customOutput').textContent=JSON.stringify(r,null,2).slice(0,12000)}catch(e){$('#customOutput').textContent=e.message}};loadSettings();
